   

- name: create ignition
  command: openshift-install create ignition-configs --dir {{ workdir.install }}

- name: adjust permissions
  file: 
    path: "{{ workdir.install }}/bootstrap.ign"
    state: file
    setype: virt_content_t
    mode: 0644

- name: adjust permissions
  file: 
    path: "{{ workdir.install }}/master.ign"
    state: file
    setype: virt_content_t
    mode: 0644    


- name: adjust permissions
  file: 
    path: "{{ workdir.install }}/worker.ign"
    state: file
    setype: virt_content_t  
    mode: 0644

- name: add podman policy to ignition
  template:
    src: podman-policy.yaml.j2
    dest: "{{ item }}"
  with_items:
    - "{{ workdir.install }}/master.ign"
    - "{{ workdir.install }}/worker.ign"
    - "{{ workdir.install }}/bootstrap.ign"
  when: cluster.use_mirror    

  