- name: prepare image for bootstrap
  include: prepare-image.yaml 
  with_items:
  - '{{ cluster.compute.bootstrap }}'

- name: prepare image for masters
  include: prepare-image.yaml   
  with_items: '{{ cluster.compute.masters }}'    

- name: create bootstrap
  virt:
    command: define
    xml: '{{ lookup("template", "vm-template.xml.j2") }}'
  with_items: 
  - '{{ cluster.compute.bootstrap }}'

- name: create masters
  virt:
    command: define
    xml: '{{ lookup("template", "vm-template.xml.j2") }}'
  with_items: '{{ cluster.compute.masters }}'

- name: start bootstrap
  virt:
    state: running
    name: '{{ item.name }}.{{ cluster.compute.vms_domain }}'
  with_items:
  - '{{ cluster.compute.bootstrap }}'

- name: start masters
  virt:
    state: running
    name: '{{ item.name }}.{{ cluster.compute.vms_domain }}'
  with_items: '{{ cluster.compute.masters }}' 
  
- name: Waiting since {{ ansible_date_time.time }} for the bootstrap to complete. On a laptop it can take much longer, we are going to try for 4 times.
  command: |
    openshift-install wait-for bootstrap-complete --dir "{{ workdir.install }}" 
  register: task_result
  until: task_result.rc == 0
  retries: 4
  delay: 60    

