
base_image_name: rhcos-43.81.202001031653.0-qemu.x86_64.qcow2
base_image_url: https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.3/43.81.202001031653.0/x86_64/rhcos-43.81.202001031653.0-qemu.x86_64.qcow2.gz

#base_image_url: https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/rhcos-4.4/44.81.202002140030-0/x86_64/rhcos-44.81.202002140030-0-qemu.x86_64.qcow2.gz
#base_image_name: rhcos-44.81.202002140030-0-qemu.x86_64.qcow2

fcos_image_url: https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/31.20200118.3.0/x86_64/fedora-coreos-31.20200118.3.0-qemu.x86_64.qcow2.xz
fcos_image_name: fedora-coreos-31.20200118.3.0-qemu.x86_64.qcow2
#base_image_name: rhcos-410.8.20190604.0-qemu.qcow2
#base_image_url: https://releases-rhcos-art.cloud.privileged.psi.redhat.com/storage/releases/ootpa/410.8.20190604.0/rhcos-410.8.20190604.0-qemu.qcow2



workdir:
  vm_data: /home/rspazzol/git/ocp4-ansible-libvirt/vms
  install: /home/rspazzol/git/ocp4-ansible-libvirt/install
  registry_mirror: /home/rspazzol/git/ocp4-ansible-libvirt/registry-mirror

mirror:
  username: raffa
  password: raffa
  pull_secret_file: pull_secret.json
  sigstore: https://mirror.openshift.com/pub/openshift-v4/signatures/
  tang_secret: PLjNyRdGw03zlRoGjQYMahSZGu9

cluster:
  version: 4.3.0
  #obstain this by doing 'openshift-install version'
  release_image: quay.io/openshift-release-dev/ocp-release@sha256:3a516480dfd68e0f87f702b4d7bdd6f6a0acfdac5cd2e9767b838ceede34d70d
  use_mirror: true
  use_tpm: false
  use_tang: false
  compute:
    vms_domain: "{{ install_config.metadata.name }}.{{ install_config.baseDomain }}"
    registry_mirror:
      name: registry-mirror
      ip: '192.168.131.10'
      mac: '52:54:00:2c:01:10'
      #memory: 8192
      memory: 2048
      cpus: 2
      image_file_name: "{{ workdir.vm_data }}/registry-mirror.qcow2"
      ign_file_name: "{{ workdir.registry_mirror }}/registry-mirror.ign"
    bootstrap:
      name: bootstrap
      ip: '192.168.131.11'
      mac: '52:54:00:2c:01:11'
      #memory: 8192
      memory: 4096
      cpus: 2
      image_file_name: "{{ workdir.vm_data }}/bootstrap.qcow2"
      ign_file_name: "{{ workdir.install }}/bootstrap.ign"
    masters:
    - name: master-1
      ip: '192.168.131.12'
      mac: '52:54:00:2c:01:12'      
      #memory: 10240
      memory: 16384
      cpus: 6
      image_file_name: "{{ workdir.vm_data }}/master-1.qcow2"
      ign_file_name: "{{ workdir.install }}/master.ign"
    # - name: master-2
    #   ip: '192.168.131.13'
    #   mac: '52:54:00:2c:01:13'      
    #   memory: 10240
    #   #memory: 16384
    #   cpus: 6
    #   image_file_name: "{{ workdir.vm_data }}/master-2.qcow2"
    #   ign_file_name: "{{ workdir.install }}/master.ign"
    # - name: master-3
    #   ip: '192.168.131.14'
    #   mac: '52:54:00:2c:01:14'      
    #   memory: 10240
    #   #memory: 16384
    #   cpus: 6
    #   image_file_name: "{{ workdir.vm_data }}/master-3.qcow2"
    #   ign_file_name: "{{ workdir.install }}/master.ign"           
    workers:
    - name: worker-1
      ip: '192.168.131.15'
      mac: '52:54:00:2c:01:15'
      #memory: 8192
      memory: 4096
      cpus: 2
      image_file_name: "{{ workdir.vm_data }}/worker-1.qcow2"
      ign_file_name: "{{ workdir.install }}/worker.ign"      
  network:
    dhcp:
      min: 192.168.131.10
      max: 192.168.131.128
    bridge:
      default_route: 192.168.131.1
      mac:  52:54:00:2c:01:00
      netmask: '255.255.255.0'
    lb:
      api: 192.168.131.3
      apps: 192.168.131.129
    ocp_managed:
      allowed_cidr: 192.168.131.128/26
      autoassigned_cidr: 192.168.131.192/26  
      
    
install_config:
  apiVersion: v1
  baseDomain: mylaptop.io
  compute:
  - hyperthreading: Enabled
    name: worker
    platform: {}
    replicas: 0
  controlPlane:
    hyperthreading: Enabled
    name: master
    platform: {}
    replicas: 1
  metadata:
    name: ocp4-libvirt
  platform:
    none: {}  
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
    machineCIDR: 192.168.131.0/24
    networkType: OpenShiftSDN
    serviceNetwork:
    - 172.30.0.0/16
#  pullSecret: "{{ lookup('file', lookup('env','PULL_SECRET_FILE')) | quote }}"
#  sshKey: "{{ lookup('file', lookup('env','PUBLIC_SSH_KEY_FILE')) }}"